description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Lato"
      fonts: 
        - 
          asset: "fonts/Lato-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Lato-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Poppins"
      fonts: 
        - 
          asset: "fonts/Poppins-800.ttf"
          style: "normal"
          weight: 800
        - 
          asset: "fonts/Poppins-700.ttf"
          style: "normal"
          weight: 700
    - 
      family: "Mulish"
      fonts: 
        - 
          asset: "fonts/Mulish-600italic.ttf"
          style: "italic"
          weight: 600
        - 
          asset: "fonts/Mulish-600.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/Mulish-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Mulish-900.ttf"
          style: "normal"
          weight: 900
        - 
          asset: "fonts/Mulish-700.ttf"
          style: "normal"
          weight: 700
  uses-material-design: true
