import 'package:flutter/material.dart';
import 'package:flutterapp/resolve_aquiapp/generated8specificconflictsdeslogadowidget/generated/GeneratedRectangle2613Widget1.dart';
import 'package:flutterapp/resolve_aquiapp/generated8specificconflictsdeslogadowidget/generated/GeneratedChatAreaWidget3.dart';
import 'package:flutterapp/resolve_aquiapp/generated8specificconflictsdeslogadowidget/generated/GeneratedTopBarWidget7.dart';
import 'package:flutterapp/resolve_aquiapp/generated8specificconflictsdeslogadowidget/generated/GeneratedRectangle2614Widget1.dart';
import 'package:flutterapp/resolve_aquiapp/generated8specificconflictsdeslogadowidget/generated/GeneratedChatAreaWidget2.dart';
import 'package:flutterapp/resolve_aquiapp/generated8specificconflictsdeslogadowidget/generated/GeneratedInputMessageFieldWidget1.dart';

/* Frame 8. Specific Conflicts (deslogado)
    Autogenerated by FlutLab FTF Generator
  */
class Generated8SpecificConflictsdeslogadoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(24.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(24.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(24.0),
                child: Container(
                  color: Color.fromARGB(255, 247, 247, 252),
                ),
              ),
              Positioned(
                left: -1.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 633.0,
                child: GeneratedRectangle2613Widget1(),
              ),
              Positioned(
                left: -1.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 633.0,
                child: GeneratedRectangle2614Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 667.0,
                child: GeneratedChatAreaWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 667.0,
                child: GeneratedChatAreaWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.46427917480469,
                child: GeneratedInputMessageFieldWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 90.0,
                child: GeneratedTopBarWidget7(),
              )
            ]),
      ),
    ));
  }
}
