import 'package:flutter/material.dart';
import 'package:flutterapp/resolve_aquiapp/generated5interationswidget/generated/GeneratedInputWidget2.dart';
import 'package:flutterapp/resolve_aquiapp/generated5interationswidget/generated/GeneratedDividerLineWidget1.dart';
import 'package:flutterapp/resolve_aquiapp/generated5interationswidget/generated/GeneratedBottomBarWidget6.dart';
import 'package:flutterapp/resolve_aquiapp/generated5interationswidget/generated/GeneratedContentContentBlockSmallWidget.dart';
import 'package:flutterapp/resolve_aquiapp/generated5interationswidget/generated/GeneratedTopBarWidget4.dart';
import 'package:flutterapp/resolve_aquiapp/generated5interationswidget/generated/GeneratedChatStackWidget6.dart';

/* Frame 5. Interations
    Autogenerated by FlutLab FTF Generator
  */
class Generated5InterationsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(24.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(24.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(24.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 90.0,
                child: GeneratedTopBarWidget4(),
              ),
              Positioned(
                left: 24.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 36.0,
                child: GeneratedInputWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 76.5000228881836,
                child: GeneratedContentContentBlockSmallWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 56.0,
                child: GeneratedChatStackWidget6(),
              ),
              Positioned(
                left: 24.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 0.0,
                child: GeneratedDividerLineWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.0,
                child: GeneratedBottomBarWidget6(),
              )
            ]),
      ),
    ));
  }
}
