import 'package:flutter/material.dart';
import 'package:flutterapp/resolve_aquiapp/generated6profilewidget/generated/GeneratedPersonalChatBubbleWidget9.dart';
import 'package:flutterapp/resolve_aquiapp/generated6profilewidget/generated/GeneratedTopBarWidget5.dart';
import 'package:flutterapp/resolve_aquiapp/generated6profilewidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/resolve_aquiapp/generated6profilewidget/generated/GeneratedBottomBarWidget7.dart';
import 'package:flutterapp/resolve_aquiapp/generated6profilewidget/generated/GeneratedPersonalChatBubbleWidget10.dart';
import 'package:flutterapp/resolve_aquiapp/generated6profilewidget/generated/GeneratedFrame3316Widget.dart';

/* Frame 6.Profile
    Autogenerated by FlutLab FTF Generator
  */
class Generated6ProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(24.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(24.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(24.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.0,
                child: GeneratedBottomBarWidget7(),
              ),
              Positioned(
                left: 91.0,
                top: 106.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 196.0,
                child: GeneratedFrame3316Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 284.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 89.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 51.0,
                child: GeneratedPersonalChatBubbleWidget9(),
              ),
              Positioned(
                left: 19.0,
                top: 458.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 51.0,
                child: GeneratedPersonalChatBubbleWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 90.0,
                child: GeneratedTopBarWidget5(),
              )
            ]),
      ),
    ));
  }
}
