import 'package:flutter/material.dart';
import 'package:flutterapp/resolve_aquiapp/generated1loginwidget/generated/GeneratedWelcomeWidget.dart';
import 'package:flutterapp/resolve_aquiapp/generated1loginwidget/generated/GeneratedTopBarWidget.dart';
import 'package:flutterapp/resolve_aquiapp/generated1loginwidget/generated/GeneratedDataWidget.dart';
import 'package:flutterapp/resolve_aquiapp/generated1loginwidget/generated/GeneratedAvanarWidget.dart';
import 'package:flutterapp/resolve_aquiapp/generated1loginwidget/generated/GeneratedResolveAquiWidget.dart';
import 'package:flutterapp/resolve_aquiapp/generated1loginwidget/generated/GeneratedBottomBarWidget2.dart';
import 'package:flutterapp/resolve_aquiapp/generated1loginwidget/generated/GeneratedIconWidget.dart';
import 'package:flutterapp/resolve_aquiapp/generated1loginwidget/generated/GeneratedSupervisor_accountWidget1.dart';

/* Frame 1.Login
    Autogenerated by FlutLab FTF Generator
  */
class Generated1LoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(24.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(24.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(24.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 30.0,
                top: 292.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 114.0,
                child: GeneratedDataWidget(),
              ),
              Positioned(
                left: 160.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 23.0,
                child: GeneratedAvanarWidget(),
              ),
              Positioned(
                left: 171.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 20.0,
                child: GeneratedIconWidget(),
              ),
              Positioned(
                left: 329.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 31.034482955932617,
                height: 28.363637924194336,
                child: GeneratedSupervisor_accountWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.0,
                child: GeneratedBottomBarWidget2(),
              ),
              Positioned(
                left: 62.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 149.0,
                child: GeneratedWelcomeWidget(),
              ),
              Positioned(
                left: 128.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 35.0,
                child: GeneratedResolveAquiWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 46.0,
                child: GeneratedTopBarWidget(),
              )
            ]),
      ),
    ));
  }
}
