import 'package:flutter/material.dart';
import 'package:flutterapp/resolve_aquiapp/generated3addwidget/generated/GeneratedContactListWidget.dart';
import 'package:flutterapp/resolve_aquiapp/generated3addwidget/generated/GeneratedBottomBarWidget4.dart';
import 'package:flutterapp/resolve_aquiapp/generated3addwidget/generated/GeneratedTopBarWidget2.dart';
import 'package:flutterapp/resolve_aquiapp/generated3addwidget/generated/GeneratedBottomBarWidget5.dart';

/* Frame 3. Add
    Autogenerated by FlutLab FTF Generator
  */
class Generated3AddWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(24.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(24.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(24.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 407.0,
                child: GeneratedContactListWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 53.0,
                child: GeneratedBottomBarWidget4(),
              ),
              Positioned(
                left: 2.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.0,
                child: GeneratedBottomBarWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 90.0,
                child: GeneratedTopBarWidget2(),
              )
            ]),
      ),
    ));
  }
}
