import 'package:flutter/material.dart';
import 'package:flutterapp/resolve_aquiapp/generated4specificconflictswidget/generated/GeneratedRectangle2614Widget.dart';
import 'package:flutterapp/resolve_aquiapp/generated4specificconflictswidget/generated/GeneratedChatAreaWidget1.dart';
import 'package:flutterapp/resolve_aquiapp/generated4specificconflictswidget/generated/GeneratedRectangle2613Widget.dart';
import 'package:flutterapp/resolve_aquiapp/generated4specificconflictswidget/generated/GeneratedChatAreaWidget.dart';
import 'package:flutterapp/resolve_aquiapp/generated4specificconflictswidget/generated/GeneratedInputMessageFieldWidget.dart';
import 'package:flutterapp/resolve_aquiapp/generated4specificconflictswidget/generated/GeneratedTopBarWidget3.dart';

/* Frame 4. Specific Conflicts
    Autogenerated by FlutLab FTF Generator
  */
class Generated4SpecificConflictsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(24.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(24.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(24.0),
                child: Container(
                  color: Color.fromARGB(255, 247, 247, 252),
                ),
              ),
              Positioned(
                left: -1.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 633.0,
                child: GeneratedRectangle2613Widget(),
              ),
              Positioned(
                left: -1.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 633.0,
                child: GeneratedRectangle2614Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 667.0,
                child: GeneratedChatAreaWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 667.0,
                child: GeneratedChatAreaWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.46427917480469,
                child: GeneratedInputMessageFieldWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 90.0,
                child: GeneratedTopBarWidget3(),
              )
            ]),
      ),
    ));
  }
}
